// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)
