app = 'fermented-food'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
app = "bundle exec rails server -p 3000"
worker = "bundle exec sidekiq"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
