default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: fermented_food_test
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  username: <%= ENV.fetch("PGUSER", nil) %>
  password: <%= ENV.fetch("PGPASSWORD", nil) %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
